pdfjsLib.GlobalWorkerOptions.workerSrc =
  'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';

  /* ---------- text lines ---------- */
  function buildLines(items, vp) {
    var list = [];
      items.forEach(function (it) {
          if (!it.str || !it.str.trim()) return;
              var p = vp.convertToViewportPoint(it.transform[4], it.transform[5]);
                  list.push({
                        str: it.str, x: p[0], y: p[1], w: it.width,
                              size: Math.abs(it.transform[3]) || it.height || 8
                                  });
                                    });
                                      list.sort(function (a, b) { return a.y - b.y || a.x - b.x; });

                                        var rows = [];
                                          list.forEach(function (it) {
                                              var r = rows[rows.length - 1];
                                                  if (r && Math.abs(it.y - r.y) <= Math.max(2, it.size * 0.4)) r.items.push(it);
                                                      else rows.push({ y: it.y, items: [it] });
                                                        });

                                                          return rows.map(function (r) {
                                                              r.items.sort(function (a, b) { return a.x - b.x; });
                                                                  var cells = [], cur = null, prevEnd = null, size = 0;
                                                                      r.items.forEach(function (it) {
                                                                            size = Math.max(size, it.size);
                                                                                  var gap = prevEnd === null ? 0 : it.x - prevEnd;
                                                                                        if (cur === null || gap > it.size * 1.5) {
                                                                                                cur = { text: it.str, x: it.x };
                                                                                                        cells.push(cur);
                                                                                                              } else {
                                                                                                                      cur.text += (gap > it.size * 0.12 ? ' ' : '') + it.str;
                                                                                                                            }
                                                                                                                                  prevEnd = it.x + it.w;
                                                                                                                                      });
                                                                                                                                          cells.forEach(function (c) { c.text = c.text.replace(/\s+/g, ' ').trim(); });
                                                                                                                                              cells = cells.filter(function (c) { return c.text; });
                                                                                                                                                  return {
                                                                                                                                                        y: r.y, x: cells.length ? cells[0].x : 0, size: size, cells: cells,
                                                                                                                                                              text: cells.map(function (c) { return c.text; }).join(' ')
                                                                                                                                                                  };
                                                                                                                                                                    }).filter(function (l) { return l.cells.length; });
                                                                                                                                                                    }

                                                                                                                                                                    /* ---------- images / diagrams ---------- */
                                                                                                                                                                    function overlap(a, b) {
                                                                                                                                                                      return a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;
                                                                                                                                                                      }
                                                                                                                                                                      function union(a, b) {
                                                                                                                                                                        var x = Math.min(a.x, b.x), y = Math.min(a.y, b.y);
                                                                                                                                                                          return { x: x, y: y, w: Math.max(a.x + a.w, b.x + b.w) - x, h: Math.max(a.y + a.h, b.y + b.h) - y };
                                                                                                                                                                          }
                                                                                                                                                                          function mergeRects(r) {
                                                                                                                                                                            var again = true;
                                                                                                                                                                              while (again) {
                                                                                                                                                                                  again = false;
                                                                                                                                                                                      for (var i = 0; i < r.length && !again; i++) {
                                                                                                                                                                                            for (var j = i + 1; j < r.length; j++) {
                                                                                                                                                                                                    if (overlap(r[i], r[j])) {
                                                                                                                                                                                                              r[i] = union(r[i], r[j]); r.splice(j, 1); again = true; break;
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                    return r;
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    async function getImages(page, vp) {
                                                                                                                                                                                                                                      var ops = await page.getOperatorList();
                                                                                                                                                                                                                                        var O = pdfjsLib.OPS, U = pdfjsLib.Util;
                                                                                                                                                                                                                                          var imgOps = [O.paintImageXObject, O.paintInlineImageXObject, O.paintImageMaskXObject];
                                                                                                                                                                                                                                            var ctm = [1, 0, 0, 1, 0, 0], stack = [], rects = [];

                                                                                                                                                                                                                                              for (var i = 0; i < ops.fnArray.length; i++) {
                                                                                                                                                                                                                                                  var fn = ops.fnArray[i], a = ops.argsArray[i];
                                                                                                                                                                                                                                                      if (fn === O.save) stack.push(ctm.slice());
                                                                                                                                                                                                                                                          else if (fn === O.paintFormXObjectBegin) {
                                                                                                                                                                                                                                                                stack.push(ctm.slice());
                                                                                                                                                                                                                                                                      if (a && a[0]) ctm = U.transform(ctm, a[0]);
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                              else if (fn === O.restore || fn === O.paintFormXObjectEnd) { if (stack.length) ctm = stack.pop(); }
                                                                                                                                                                                                                                                                                  else if (fn === O.transform) ctm = U.transform(ctm, a);
                                                                                                                                                                                                                                                                                      else if (imgOps.indexOf(fn) !== -1) {
                                                                                                                                                                                                                                                                                            var xs = [], ys = [];
                                                                                                                                                                                                                                                                                                  [[0, 0], [1, 0], [0, 1], [1, 1]].forEach(function (pt) {
                                                                                                                                                                                                                                                                                                          var q = U.applyTransform(pt, ctm);
                                                                                                                                                                                                                                                                                                                  var v = vp.convertToViewportPoint(q[0], q[1]);
                                                                                                                                                                                                                                                                                                                          xs.push(v[0]); ys.push(v[1]);
                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                      var x = Math.max(0, Math.min.apply(null, xs)), y = Math.max(0, Math.min.apply(null, ys));
                                                                                                                                                                                                                                                                                                                                            var x2 = Math.min(vp.width, Math.max.apply(null, xs)), y2 = Math.min(vp.height, Math.max.apply(null, ys));
                                                                                                                                                                                                                                                                                                                                                  if (x2 - x >= 24 && y2 - y >= 24) rects.push({ x: x, y: y, w: x2 - x, h: y2 - y });
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                          rects = mergeRects(rects);
                                                                                                                                                                                                                                                                                                                                                            if (!rects.length) return [];

                                                                                                                                                                                                                                                                                                                                                              var sc = 2, v2 = page.getViewport({ scale: sc });
                                                                                                                                                                                                                                                                                                                                                                var cv = document.createElement('canvas');
                                                                                                                                                                                                                                                                                                                                                                  cv.width = v2.width; cv.height = v2.height;
                                                                                                                                                                                                                                                                                                                                                                    var ctx = cv.getContext('2d');
                                                                                                                                                                                                                                                                                                                                                                      ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, cv.width, cv.height);
                                                                                                                                                                                                                                                                                                                                                                        await page.render({ canvasContext: ctx, viewport: v2 }).promise;

                                                                                                                                                                                                                                                                                                                                                                          rects.forEach(function (r) {
                                                                                                                                                                                                                                                                                                                                                                              var c = document.createElement('canvas');
                                                                                                                                                                                                                                                                                                                                                                                  c.width = Math.round(r.w * sc); c.height = Math.round(r.h * sc);
                                                                                                                                                                                                                                                                                                                                                                                      c.getContext('2d').drawImage(cv, r.x * sc, r.y * sc, r.w * sc, r.h * sc, 0, 0, c.width, c.height);
                                                                                                                                                                                                                                                                                                                                                                                          r.src = c.toDataURL('image/png');
                                                                                                                                                                                                                                                                                                                                                                                              r.full = (r.w * r.h) / (vp.width * vp.height) > 0.85;
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                  return rects;
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                  /* ---------- blocks ---------- */
                                                                                                                                                                                                                                                                                                                                                                                                  var BULLET = /^(\u2022|\u25AA|\u25CF|\u25E6|\u2023|-|\u2013|\*|\d+[.)]|[a-zA-Z][.)]|\([a-zA-Z0-9]+\))\s+/;

                                                                                                                                                                                                                                                                                                                                                                                                  function buildBlocks(p, body) {
                                                                                                                                                                                                                                                                                                                                                                                                    var items = [], L = p.lines, i = 0, cur = null;

                                                                                                                                                                                                                                                                                                                                                                                                      function flush() {
                                                                                                                                                                                                                                                                                                                                                                                                          if (cur) { items.push({ y: cur.y, b: { type: cur.type, text: cur.text } }); cur = null; }
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                              while (i < L.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                  var l = L[i];

                                                                                                                                                                                                                                                                                                                                                                                                                      if (l.cells.length >= 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                            var run = [l], j = i + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                  while (j < L.length && L[j].cells.length >= 2) { run.push(L[j]); j++; }
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (run.length >= 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                flush();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        items.push({ y: l.y, b: { type: 'table', rows: run.map(function (r) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return r.cells.map(function (c) { return c.text; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }) } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  i = j; continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (l.size >= body * 1.12 && l.text.length <= 150) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flush();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var last = items[items.length - 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (last && last.b.type === 'h' && Math.abs(last.size - l.size) < 0.6 && (l.y - last.lastY) < l.size * 1.8) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          last.b.text += ' ' + l.text; last.lastY = l.y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        items.push({ y: l.y, size: l.size, lastY: l.y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  b: { type: 'h', level: l.size >= body * 1.5 ? 1 : 2, text: l.text } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              i++; continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (BULLET.test(l.text)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flush();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cur = { type: 'li', text: l.text, y: l.y, lastY: l.y };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else if (cur && (l.y - cur.lastY) <= l.size * 1.6) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.text += ' ' + l.text; cur.lastY = l.y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flush();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur = { type: 'p', text: l.text, y: l.y, lastY: l.y };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    i++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flush();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          p.imgs.forEach(function (im) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              items.push({ y: im.y, b: { type: 'img', src: im.src } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  items.sort(function (a, b) { return a.y - b.y; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return items.map(function (x) { return x.b; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* ---------- main ---------- */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function extractPDF(file, onProgress) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var pdf = await pdfjsLib.getDocument({ data: await file.arrayBuffer() }).promise;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var pages = [], sizeMap = {}, scanned = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for (var n = 1; n <= pdf.numPages; n++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onProgress('Page ' + n + ' / ' + pdf.numPages + ' padh raha hu...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var page = await pdf.getPage(n);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var vp = page.getViewport({ scale: 1 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var tc = await page.getTextContent();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              var lines = buildLines(tc.items, vp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var imgs = await getImages(page, vp);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (imgs.some(function (m) { return m.full; })) scanned++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          lines = lines.filter(function (l) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return !imgs.some(function (m) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return l.x >= m.x && l.x <= m.x + m.w && l.y >= m.y && l.y <= m.y + m.h;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      lines.forEach(function (l) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var k = Math.round(l.size * 2) / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  sizeMap[k] = (sizeMap[k] || 0) + l.text.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pages.push({ lines: lines, imgs: imgs });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              var body = 10, best = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Object.keys(sizeMap).forEach(function (k) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (sizeMap[k] > best) { best = sizeMap[k]; body = parseFloat(k); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var blocks = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pages.forEach(function (p) { blocks = blocks.concat(buildBlocks(p, body)); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { blocks: blocks, pageCount: pdf.numPages, bodySize: body, scanned: scanned };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }