// --- 1. CUSTOM CURSOR & ANIMATIONS ---
const cursor = document.getElementById('cursor');
const trail = document.getElementById('cursor-trail');
let mx = 0, my = 0, tx = 0, ty = 0;

document.addEventListener('mousemove', e => {
  mx = e.clientX; my = e.clientY;
    cursor.style.left = mx - 6 + 'px';
      cursor.style.top = my - 6 + 'px';
      });

      function animTrail() {
        tx += (mx - tx) * 0.12;
          ty += (my - ty) * 0.12;
            trail.style.left = tx - 18 + 'px';
              trail.style.top = ty - 18 + 'px';
                requestAnimationFrame(animTrail);
                }
                animTrail();

                document.querySelectorAll('a, button, .feature-card, input').forEach(el => {
                  el.addEventListener('mouseenter', () => {
                      cursor.style.transform = 'scale(2.5)';
                          trail.style.transform = 'scale(1.4)';
                            });
                              el.addEventListener('mouseleave', () => {
                                  cursor.style.transform = 'scale(1)';
                                      trail.style.transform = 'scale(1)';
                                        });
                                        });

                                        // --- 2. COUNTER & SCROLL REVEAL ---
                                        function animateCounter(el, target, duration = 1800) {
                                          let start = 0;
                                            const step = timestamp => {
                                                if (!start) start = timestamp;
                                                    const progress = Math.min((timestamp - start) / duration, 1);
                                                        const ease = 1 - Math.pow(1 - progress, 3);
                                                            el.textContent = Math.floor(ease * target).toLocaleString();
                                                                if (progress < 1) requestAnimationFrame(step);
                                                                  };
                                                                    requestAnimationFrame(step);
                                                                    }

                                                                    const io = new IntersectionObserver((entries) => {
                                                                      entries.forEach(e => {
                                                                          if (e.isIntersecting) {
                                                                                e.target.classList.add('visible');
                                                                                      e.target.querySelectorAll('.counter').forEach(c => {
                                                                                              animateCounter(c, parseInt(c.dataset.target));
                                                                                                    });
                                                                                                        }
                                                                                                          });
                                                                                                          }, { threshold: 0.15 });

                                                                                                          document.querySelectorAll('.reveal, .stats-bar').forEach(el => io.observe(el));

                                                                                                          // --- 3. 3D TILT EFFECT ---
                                                                                                          document.querySelectorAll('.tilt-card').forEach(card => {
                                                                                                            card.addEventListener('mousemove', e => {
                                                                                                                const r = card.getBoundingClientRect();
                                                                                                                    const x = (e.clientX - r.left) / r.width - 0.5;
                                                                                                                        const y = (e.clientY - r.top) / r.height - 0.5;
                                                                                                                            card.style.transform = `perspective(800px) rotateX(${-y * 6}deg) rotateY(${x * 6}deg)`;
                                                                                                                              });
                                                                                                                                card.addEventListener('mouseleave', () => {
                                                                                                                                    card.style.transform = 'perspective(800px) rotateX(0) rotateY(0)';
                                                                                                                                      });
                                                                                                                                      });


                                                                                                                                      // --- 4. JOIN MODAL & IP LOCK LOGIC ---
                                                                                                                                      const joinModal = document.getElementById('join-modal');
                                                                                                                                      const closeModal = document.querySelector('.close-modal');
                                                                                                                                      const saveBtn = document.getElementById('save-identity-btn');
                                                                                                                                      const nameInput = document.getElementById('anon-name-input');
                                                                                                                                      const modalText = document.querySelector('.modal-content p');
                                                                                                                                      const joinButtons = document.querySelectorAll('.nav-cta, #hero .btn-primary');
                                                                                                                                      const whisperBtn = document.querySelector('#whisper .btn-primary');

                                                                                                                                      let currentIpCode = null;

                                                                                                                                      // Convert IP to a Unique Roll No/Code (Hash)
                                                                                                                                      function generateIpCode(str) {
                                                                                                                                        let hash = 0;
                                                                                                                                          for (let i = 0; i < str.length; i++) {
                                                                                                                                              let char = str.charCodeAt(i);
                                                                                                                                                  hash = ((hash << 5) - hash) + char;
                                                                                                                                                      hash = hash & hash;
                                                                                                                                                        }
                                                                                                                                                          return "CV-" + Math.abs(hash).toString(16).toUpperCase(); 
                                                                                                                                                          }

                                                                                                                                                          // Open Modal and Fetch IP
                                                                                                                                                          async function openModal(e) {
                                                                                                                                                            e.preventDefault();
                                                                                                                                                              joinModal.classList.add('show');
                                                                                                                                                                
                                                                                                                                                                  // Setup loading state
                                                                                                                                                                    saveBtn.innerText = "Securing Connection...";
                                                                                                                                                                      saveBtn.disabled = true;
                                                                                                                                                                        nameInput.style.display = 'none';
                                                                                                                                                                          modalText.innerText = "Fetching your secure network code...";

                                                                                                                                                                            try {
                                                                                                                                                                                const response = await fetch('https://api.ipify.org?format=json');
                                                                                                                                                                                    const data = await response.json();
                                                                                                                                                                                        
                                                                                                                                                                                            currentIpCode = generateIpCode(data.ip);
                                                                                                                                                                                                const lockedName = localStorage.getItem(currentIpCode);

                                                                                                                                                                                                    if(lockedName) {
                                                                                                                                                                                                          // Returning user from same IP
                                                                                                                                                                                                                modalText.innerHTML = `Network Code: <b>${currentIpCode}</b><br><br>Identity locked to: <b style="color:var(--accent)">${lockedName}</b>`;
                                                                                                                                                                                                                      saveBtn.innerText = "Enter CampusVerse";
                                                                                                                                                                                                                            saveBtn.disabled = false;
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                        saveBtn.onclick = () => {
                                                                                                                                                                                                                                                updateUIForJoinedUser(lockedName);
                                                                                                                                                                                                                                                        joinModal.classList.remove('show');
                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                        // New user from this IP
                                                                                                                                                                                                                                                                              modalText.innerHTML = `Network Code: <b>${currentIpCode}</b><br><br>Choose your anonymous name carefully. It will be permanently locked to this device.`;
                                                                                                                                                                                                                                                                                    nameInput.style.display = 'block';
                                                                                                                                                                                                                                                                                          nameInput.value = ''; 
                                                                                                                                                                                                                                                                                                saveBtn.innerText = "Lock Identity & Join";
                                                                                                                                                                                                                                                                                                      saveBtn.disabled = false;
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                  saveBtn.onclick = () => {
                                                                                                                                                                                                                                                                                                                          const chosenName = nameInput.value.trim();
                                                                                                                                                                                                                                                                                                                                  if (chosenName.length < 3) {
                                                                                                                                                                                                                                                                                                                                            alert("Name must be at least 3 characters long!");
                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                              // Lock the name to the IP code
                                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem(currentIpCode, chosenName);
                                                                                                                                                                                                                                                                                                                                                                                              localStorage.setItem('campus_identity', chosenName);
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                              updateUIForJoinedUser(chosenName);
                                                                                                                                                                                                                                                                                                                                                                                                                      joinModal.classList.remove('show');
                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                      modalText.innerText = "Network error. Try again.";
                                                                                                                                                                                                                                                                                                                                                                                                                                          saveBtn.innerText = "Retry";
                                                                                                                                                                                                                                                                                                                                                                                                                                              saveBtn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  saveBtn.onclick = openModal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    joinButtons.forEach(btn => btn.addEventListener('click', openModal));
                                                                                                                                                                                                                                                                                                                                                                                                                                                    closeModal.addEventListener('click', () => joinModal.classList.remove('show'));

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Update UI Function
                                                                                                                                                                                                                                                                                                                                                                                                                                                    function updateUIForJoinedUser(name) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const navCta = document.querySelector('.nav-cta');
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(navCta) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            navCta.innerText = name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                navCta.style.background = 'rgba(200,255,62,0.1)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    navCta.style.color = 'var(--accent)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        navCta.style.border = '1px solid var(--accent)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(whisperBtn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                whisperBtn.innerText = `Enter as ${name} →`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    whisperBtn.href = "#"; // Link for actual chat page goes here
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Auto Check on Load
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.onload = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const savedName = localStorage.getItem('campus_identity');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(savedName) updateUIForJoinedUser(savedName);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          